## System Checks

In [1]:
import sys
import os
print(sys.executable)
print(os.getcwd())

/home/pooja-saxena/.venvs/vacoda/bin/python
/home/pooja-saxena/PoojaVault/Professional/Workbench/Projects/Employment/Thunen/VACODA/notebooks

In [2]:
import sys
for p in sys.path[:10]:
    print(p)

/usr/lib/python312.zip
/usr/lib/python3.12
/usr/lib/python3.12/lib-dynload

/home/pooja-saxena/.venvs/vacoda/lib/python3.12/site-packages
/home/pooja-saxena/PoojaVault/Professional/Workbench/Projects/Employment/Thunen/VACODA/src

In [3]:
import importlib.util
importlib.util.find_spec("vacoda")

ModuleSpec(name='vacoda', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7bd5c2b205c0>, origin='/home/pooja-saxena/PoojaVault/Professional/Workbench/Projects/Employment/Thunen/VACODA/src/vacoda/__init__.py', submodule_search_locations=['/home/pooja-saxena/PoojaVault/Professional/Workbench/Projects/Employment/Thunen/VACODA/src/vacoda'])

## Read Data

In [11]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [ ]:
import importlib
import vacoda.io.loaders as loaders
importlib.reload(loaders)

config = loaders.load_config()
bundle = loaders.load_raw_bundle()
bundle.keys()

dict_keys(['main', 'hs_version', 'reporter', 'commodity', 'flow', 'unit', 'estimation'])

In [14]:
df = bundle["main"].copy()
df.head()

,CD_ID,CD_HS,CD_Reporter,CD_Partner,CD_Commodity,CD_Year,CD_Flow,CD_Unit,CD_Value,CD_ReportedCurrency,...,CD_UnitMult,CD_Decimals,CD_IDUpload,CD_IDReporter,CD_IDPartner,CD_IDCommodity,CD_IDUnit,CD_as_reported,CD_Netweight_kg/Value,CD_ActionType
0,80630069,H3,100,124,441012,2011,1,8,319186,BGN,...,1.0,1.0,234,35,41,21960,108,1.0,2.271080,I
1,80630182,H3,100,156,441012,2011,1,8,171644,BGN,...,1.0,1.0,234,35,49,21960,108,1.0,1.898697,I
2,80630489,H3,100,196,441012,2011,2,8,518550,BGN,...,1.0,1.0,234,35,61,21960,108,1.0,2.259674,I
3,444829158,H5,100,196,441012,2018,2,8,684637,NaN,...,NaN,NaN,2605,35,61,97302,108,NaN,2.219191,U
4,444840706,H5,100,203,441012,2018,1,8,10976,NaN,...,NaN,NaN,2605,35,63,97302,108,NaN,2.046283,U

In [ ]:
from vacoda.preprocessing.base import standardize_columns

bundle = {k: standardize_columns(v) for k, v in bundle.items()}
for name, df in bundle.items():
    print(name, df.columns.tolist())

main ['CD_ID', 'CD_HS', 'CD_Reporter', 'CD_Partner', 'CD_Commodity', 'CD_Year', 'CD_Flow', 'CD_Unit', 'CD_Value', 'CD_ReportedCurrency', 'CD_ConversionFactor', 'CD_Netweight_kg', 'CD_Sup_Quantity', 'CD_EstimationCode', 'CD_ReportedClassification', 'CD_HT', 'CD_PartnerSource', 'CD_Valuation', 'CD_FlowsInDataset', 'CD_UnitMult', 'CD_Decimals', 'CD_IDUpload', 'CD_IDReporter', 'CD_IDPartner', 'CD_IDCommodity', 'CD_IDUnit', 'CD_as_reported', 'CD_Netweight_kg/Value', 'CD_ActionType']
hs_version ['HS_HSCode', 'UploadDate', 'HS_valid_from', 'HS_valid_until', 'HS_HSCode2']
reporter ['Country_ID', 'Country_ISONUM', 'Country_ISO3166A2', 'Country_ISO3166A3', 'Country_Abbreviation', 'Country_StartValidYear', 'Country_EndValidYear', 'UploadDate']
commodity ['HS_ID', 'HS_HSCode', 'HS_CommodityCode', 'HS_ProductDescription', 'UploadDate']
flow ['Flow_IDFlow', 'Flow_Description', 'Flow_Category', 'UploadDate']
unit ['Unit_ID', 'Unit_Token', 'Unit_ShortName', 'Unit_Description', 'Unit_IDUpload', 'Unit_UploadDate', 'Unit_DS_valid_until']
estimation ['Est_Code', 'Est_Description']

In [ ]:
from vacoda.preprocessing.trade import prepare_trade_table

trade = prepare_trade_table(bundle["main"])
trade.head()

,record_id,hs_code_short,reporter_code,partner_code,commodity_code,year,flow_code,unit_code,value_raw,reported_currency,...,CD_UnitMult,CD_Decimals,CD_IDUpload,CD_IDReporter,CD_IDPartner,CD_IDCommodity,CD_IDUnit,CD_as_reported,CD_Netweight_kg/Value,CD_ActionType
0,80630069,H3,100,124,441012,2011,1,8,319186,BGN,...,1.0,1.0,234,35,41,21960,108,1.0,2.271080,I
1,80630182,H3,100,156,441012,2011,1,8,171644,BGN,...,1.0,1.0,234,35,49,21960,108,1.0,1.898697,I
2,80630489,H3,100,196,441012,2011,2,8,518550,BGN,...,1.0,1.0,234,35,61,21960,108,1.0,2.259674,I
3,444829158,H5,100,196,441012,2018,2,8,684637,NaN,...,NaN,NaN,2605,35,61,97302,108,NaN,2.219191,U
4,444840706,H5,100,203,441012,2018,1,8,10976,NaN,...,NaN,NaN,2605,35,63,97302,108,NaN,2.046283,U

In [ ]:
from vacoda.preprocessing.build_dataset import build_decoded_dataset

decoded = build_decoded_dataset(bundle)
decoded.head()

,record_id,hs_code_short,reporter_code,partner_code,commodity_code,year,flow_code,unit_code,value_raw,reported_currency,...,partner_country_valid_until,hs_valid_from,hs_valid_until,hs_version_name,commodity_description,flow_description,flow_category,unit_short_name,unit_description,estimation_description
0,80630069,H3,100,124,441012,2011,1,8,319186,BGN,...,NaN,2007-01-01,2011-12-31,HS2007,"Oriented strand board (OSB) of wood, whether/...",Imports,M,NaN,NaN,no estimation
1,80630182,H3,100,156,441012,2011,1,8,171644,BGN,...,NaN,2007-01-01,2011-12-31,HS2007,"Oriented strand board (OSB) of wood, whether/...",Imports,M,NaN,NaN,no estimation
2,80630489,H3,100,196,441012,2011,2,8,518550,BGN,...,NaN,2007-01-01,2011-12-31,HS2007,"Oriented strand board (OSB) of wood, whether/...",Exports,X,NaN,NaN,no estimation
3,444829158,H5,100,196,441012,2018,2,8,684637,NaN,...,NaN,2017-01-01,2021-12-31,HS2017,"Oriented strand board (OSB) of wood, whether o...",Exports,X,NaN,NaN,no estimation
4,444840706,H5,100,203,441012,2018,1,8,10976,NaN,...,NaN,2017-01-01,2021-12-31,HS2017,"Oriented strand board (OSB) of wood, whether o...",Imports,M,NaN,NaN,no estimation

In [ ]:
import importlib
import vacoda.preprocessing.build_dataset as build_dataset
importlib.reload(build_dataset)

df_base = build_dataset.build_base_analytic_dataset(bundle)
df_base.head()

,record_id,hs_code_short,reporter_code,partner_code,commodity_code,year,flow_code,unit_code,value_raw,reported_currency,...,unit_short_name,unit_description,estimation_description,value_norm,is_estimated,quantity_estimated,weight_estimated,year_date,hs_mismatch,price_per_kg
0,80630069,H3,100,124,441012,2011,1,8,319186,BGN,...,NaN,NaN,no estimation,227172.017478,False,False,False,2011-01-01,False,0.313385
1,80630182,H3,100,156,441012,2011,1,8,171644,BGN,...,NaN,NaN,no estimation,122162.982612,False,False,False,2011-01-01,False,0.374848
2,80630489,H3,100,196,441012,2011,2,8,518550,BGN,...,NaN,NaN,no estimation,369191.524950,False,False,False,2011-01-01,False,0.315076
3,444829158,H5,100,196,441012,2018,2,8,684637,NaN,...,NaN,NaN,no estimation,684637.000000,False,False,False,2018-01-01,False,0.450615
4,444840706,H5,100,203,441012,2018,1,8,10976,NaN,...,NaN,NaN,no estimation,10976.000000,False,False,False,2018-01-01,False,0.488691

In [22]:
print(df_base.shape)
df_base[
    [
        "reporter_code",
        "reporter_country_name",
        "partner_code",
        "partner_country_name",
        "commodity_code",
        "commodity_description",
        "flow_code",
        "flow_description",
        "unit_code",
        "unit_description",
        "estimation_code",
        "estimation_description",
    ]
].head()

(25589, 57)

,reporter_code,reporter_country_name,partner_code,partner_country_name,commodity_code,commodity_description,flow_code,flow_description,unit_code,unit_description,estimation_code,estimation_description
0,100,Bulgaria,124,Canada,441012,"Oriented strand board (OSB) of wood, whether/...",1,Imports,8,NaN,0,no estimation
1,100,Bulgaria,156,China,441012,"Oriented strand board (OSB) of wood, whether/...",1,Imports,8,NaN,0,no estimation
2,100,Bulgaria,196,Cyprus,441012,"Oriented strand board (OSB) of wood, whether/...",2,Exports,8,NaN,0,no estimation
3,100,Bulgaria,196,Cyprus,441012,"Oriented strand board (OSB) of wood, whether o...",2,Exports,8,NaN,0,no estimation
4,100,Bulgaria,203,Czechia,441012,"Oriented strand board (OSB) of wood, whether o...",1,Imports,8,NaN,0,no estimation

In [23]:
df_base["reporter_country_name"].isna().mean()
df_base["partner_country_name"].isna().mean()
df_base["commodity_description"].isna().mean()
df_base["flow_description"].isna().mean()
df_base["unit_description"].isna().mean()
df_base["estimation_description"].isna().mean()

np.float64(0.0)

In [ ]:
import pandas as pd
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", None)

df.head(10)

In [ ]:
from vacoda.io.loaders import load_raw_bundle
from vacoda.io.paths import get_base_analytic_parquet_path
from vacoda.preprocessing.build_dataset import build_base_analytic_dataset
from vacoda.io.saver import save_parquet

bundle = load_raw_bundle()
bundle = {k: standardize_columns(v) for k, v in bundle.items()}

df_base = build_base_analytic_dataset(bundle)
output_path = get_base_analytic_parquet_path()
save_parquet(df_base, output_path)

In [ ]:
df[["CD_Value", "CD_ReportedCurrency", "CD_ConversionFactor"]].head(20)

In [ ]:
df["CD_ReportedCurrency"].value_counts(dropna=False)

In [ ]:
df.info()

In [ ]:
df.describe(include='all')

In [ ]:
df.dtypes

### Missing Values

In [ ]:
df.isna().sum().sort_values(ascending=False)

## Duplicate Values

In [ ]:
df.duplicated().sum()

In [ ]:
df['CD_HS'].unique_value()